# This docker-compose file is intended for development purposes only
version: '3'
services:
  cl2-tenant-clone:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/cl2-tenant-clone
    env_file:
      - .env

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=0
networks:
  default:
    external:
      name: citizenlab
